    - name: Build Machine Init
      hosts: localhost
      vars:
        version: "blue"
      tasks:
        - name: run build-machine
          community.docker.docker_compose:
            project_src: build-machine
        - name: Creating Project Tarball from app folder
          ansible.builtin.shell:
            cmd: tar -zcvf app_comp.tar.gz app && mv app_comp.tar.gz build/.
            chdir: /Users/ma3touch/Desktop/DevOps_Challenge/services/
        - name: Extracting app in Build
          ansible.builtin.shell:
            cmd: tar -xvf build/app_comp.tar.gz -C build/. 
            chdir: /Users/ma3touch/Desktop/DevOps_Challenge/services/



