# playbook to build dockerfile in build-machine
    - name: Build-machine init
      hosts: localhost
      tasks:
        - name: run build-machine
          community.docker.docker_compose:
            project_src: build-machine
        - name: Creating Project Tarball
          community.docker.docker_container_exec:
            container:  php_one
            command: tar -zcvf app_comp.tar.gz /app 
            chdir: /
          register: result
        - name: Moving Tarball to Build Shared Volume
          community.docker.docker_container_exec:
            container:  php_one
            command: mv /app_comp.tar.gz /build/ 
            chdir: /
          register: result
        - name: Extracting app in Build
          community.docker.docker_container_exec:
            container: php_one
            command: tar -xvf /build/app_comp.tar.gz -C /build/. 
            chdir: /
          register: result

