services:
  openresty:
    image: openresty/openresty
    container_name: openresty_service
    ports:
      - "80:80"
    volumes:
      - ./openresty/default.conf:/etc/nginx/conf.d/default.conf
      - ./openresty/default.conf:/etc/nginx/conf.d/default.conf.blue
      - ./openresty/access.log:/etc/nginx/conf.d/access.log
      - ./app_blue/:/app_blue
      - ./app_green/:/app_green
    networks:
      - productionNet
    restart: always
    depends_on:
      - blue_one
      - blue_two
      - green_one
      - green_two

  blue_one:
    image: php:7-fpm
    container_name: blue_one
    networks:
      - productionNet
    restart: always
    volumes:
      - ./app_blue/:/app_blue

  blue_two:
    image: php:7-fpm
    container_name: blue_two
    networks:
      - productionNet
    restart: always
    volumes:
      - ./app_blue/:/app_blue

  green_one:
    image: php:7-fpm
    container_name: green_one
    networks:
      - productionNet
    restart: always
    volumes:
      - ./app_green/:/app_green
    
  green_two:
    image: php:7-fpm
    container_name: green_two
    networks:
      - productionNet
    restart: always
    volumes:
      - ./app_green/:/app_green

networks:
  productionNet: