services:
  openresty_build:
    image: openresty/openresty
    container_name: openresty_build_container
    ports:
      - "5000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../services/build/:/build
    networks:
      - buildNet
    restart: always
    depends_on:
      - php_build
  php_build:
    image: php:7-fpm
    container_name: php_build_container
    networks:
      - buildNet
    restart: always
    volumes:
        - ../services/build/:/build
networks:
  buildNet: