# playbook to build dockerfile in build-machine
    - name: Build docker image
      hosts: localhost
      tasks:
        - name: Build docker image for build machine
          docker_image:
            build:
              path: .
            name: build_machine
            tag: v1
            source: build
        - name: Runing build machine
          docker_container:
            name: build_container
            image: build_machine:v1
            state: started
        - name: Creating Project Tarball
          community.docker.docker_container_exec:
            container:  php_one
            command: tar -zcvf app_comp.tar.gz /app 
            chdir: /
          register: result
        - name: Moving Tarball to Build Shared Volume
          community.docker.docker_container_exec:
            container:  php_one
            command: mv /app_comp.tar.gz /build/ 
            chdir: /
          register: result
        - name: Extracting app in Build
          community.docker.docker_container_exec:
            container:  php_one
            command: tar -xvf /build/app_comp.tar.gz -C /build/. 
            chdir: /
          register: result
